version: "3.9"
services:
  api-node:
    image: api-node
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    init: true
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
      - type: volume
        target: /usr/src/app/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3000:3000"
    restart: unless-stopped
  db:
    image: postgres:17.6-alpine3.22
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
volumes:
  pgdata:
